2025-07-08T20:37:41.497856267Z ==> Cloning from https://github.com/rehmanul/CAD-Analyzer-Pro
2025-07-08T20:37:42.675483444Z ==> Checking out commit c1a570c6c2e11fa26ec5995bc57307a44facff19 in branch main
2025-07-08T20:37:43.783805155Z ==> Downloading cache...
2025-07-08T20:38:00.917601772Z ==> Transferred 645MB in 9s. Extraction took 7s.
2025-07-08T20:38:05.86990982Z ==> Using Python version 3.13.4 (default)
2025-07-08T20:38:05.90252635Z ==> Docs on specifying a Python version: https://render.com/docs/python-version
2025-07-08T20:38:09.477352463Z ==> Using Poetry version 2.1.3 (default)
2025-07-08T20:38:09.525637807Z ==> Docs on specifying a Poetry version: https://render.com/docs/poetry-version
2025-07-08T20:38:09.546572327Z ==> Using uv version 0.7.12 (default)
2025-07-08T20:38:09.546594168Z ==> Docs on specifying a uv version: https://render.com/docs/uv-version
2025-07-08T20:38:09.559341265Z ==> Running build command 'pip install -r requirements_render.txt'...
2025-07-08T20:38:10.226089388Z Collecting streamlit==1.36.0 (from -r requirements_render.txt (line 3))
2025-07-08T20:38:10.228407516Z   Using cached streamlit-1.36.0-py2.py3-none-any.whl.metadata (8.5 kB)
2025-07-08T20:38:10.32408305Z Collecting plotly==5.24.1 (from -r requirements_render.txt (line 4))
2025-07-08T20:38:10.326305756Z   Using cached plotly-5.24.1-py3-none-any.whl.metadata (7.3 kB)
2025-07-08T20:38:10.495464605Z Collecting pandas==2.2.3 (from -r requirements_render.txt (line 5))
2025-07-08T20:38:10.496912208Z   Using cached pandas-2.2.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
2025-07-08T20:38:10.741282129Z Collecting numpy==1.26.4 (from -r requirements_render.txt (line 6))
2025-07-08T20:38:10.741505502Z   Using cached numpy-1.26.4-cp313-cp313-linux_x86_64.whl
2025-07-08T20:38:10.872132005Z Collecting shapely==2.1.0 (from -r requirements_render.txt (line 7))
2025-07-08T20:38:10.872383909Z   Using cached shapely-2.1.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
2025-07-08T20:38:11.03186512Z Collecting scipy==1.13.1 (from -r requirements_render.txt (line 8))
2025-07-08T20:38:11.03368526Z   Using cached scipy-1.13.1.tar.gz (57.2 MB)
2025-07-08T20:38:15.824313644Z   Installing build dependencies: started
2025-07-08T20:38:21.96932184Z   Installing build dependencies: finished with status 'done'
2025-07-08T20:38:22.013408236Z   Getting requirements to build wheel: started
2025-07-08T20:38:22.186929065Z   Getting requirements to build wheel: finished with status 'done'
2025-07-08T20:38:22.189368465Z   Installing backend dependencies: started
2025-07-08T20:38:22.847910424Z   Installing backend dependencies: finished with status 'done'
2025-07-08T20:38:22.848824039Z   Preparing metadata (pyproject.toml): started
2025-07-08T20:38:26.202006405Z   Preparing metadata (pyproject.toml): finished with status 'error'
2025-07-08T20:38:26.207747228Z   error: subprocess-exited-with-error
2025-07-08T20:38:26.207764728Z   
2025-07-08T20:38:26.207771598Z   Ã— Preparing metadata (pyproject.toml) did not run successfully.
2025-07-08T20:38:26.207776818Z   â”‚ exit code: 1
2025-07-08T20:38:26.207782439Z   â•°â”€> [53 lines of output]
2025-07-08T20:38:26.207787459Z       + meson setup /tmp/pip-install-r41d17sd/scipy_be578535254e4583970332105e5b3908 /tmp/pip-install-r41d17sd/scipy_be578535254e4583970332105e5b3908/.mesonpy-dulk_swy -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-r41d17sd/scipy_be578535254e4583970332105e5b3908/.mesonpy-dulk_swy/meson-python-native-file.ini
2025-07-08T20:38:26.207792739Z       The Meson build system
2025-07-08T20:38:26.207797019Z       Version: 1.8.2
2025-07-08T20:38:26.207801599Z       Source dir: /tmp/pip-install-r41d17sd/scipy_be578535254e4583970332105e5b3908
2025-07-08T20:38:26.207806569Z       Build dir: /tmp/pip-install-r41d17sd/scipy_be578535254e4583970332105e5b3908/.mesonpy-dulk_swy
2025-07-08T20:38:26.207822249Z       Build type: native build
2025-07-08T20:38:26.207825089Z       Project name: scipy
2025-07-08T20:38:26.207828439Z       Project version: 1.13.1
2025-07-08T20:38:26.20783121Z       C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14+deb12u1) 12.2.0")
2025-07-08T20:38:26.20783471Z       C linker for the host machine: cc ld.bfd 2.40
2025-07-08T20:38:26.207840999Z       C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14+deb12u1) 12.2.0")
2025-07-08T20:38:26.20784357Z       C++ linker for the host machine: c++ ld.bfd 2.40
2025-07-08T20:38:26.20784624Z       Cython compiler for the host machine: cython (cython 3.0.12)
2025-07-08T20:38:26.20784907Z       Host machine cpu family: x86_64
2025-07-08T20:38:26.20785212Z       Host machine cpu: x86_64
2025-07-08T20:38:26.20785479Z       Program python found: YES (/opt/render/project/src/.venv/bin/python)
2025-07-08T20:38:26.20785746Z       Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
2025-07-08T20:38:26.20785999Z       Run-time dependency python found: YES 3.13
2025-07-08T20:38:26.20786298Z       Program cython found: YES (/tmp/pip-build-env-phc___j1/overlay/bin/cython)
2025-07-08T20:38:26.20786552Z       Compiler for C supports arguments -Wno-unused-but-set-variable: YES
2025-07-08T20:38:26.20786806Z       Compiler for C supports arguments -Wno-unused-function: YES
2025-07-08T20:38:26.20787098Z       Compiler for C supports arguments -Wno-conversion: YES
2025-07-08T20:38:26.20787399Z       Compiler for C supports arguments -Wno-misleading-indentation: YES
2025-07-08T20:38:26.20787675Z       Library m found: YES
2025-07-08T20:38:26.20787946Z       
2025-07-08T20:38:26.20788277Z       ../meson.build:78:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang-new'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
2025-07-08T20:38:26.20788622Z       The following exception(s) were encountered:
2025-07-08T20:38:26.207889Z       Running `gfortran --help` gave "[Errno 2] No such file or directory: 'gfortran'"
2025-07-08T20:38:26.20789167Z       Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
2025-07-08T20:38:26.2078946Z       Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
2025-07-08T20:38:26.207897171Z       Running `flang-new --help` gave "[Errno 2] No such file or directory: 'flang-new'"
2025-07-08T20:38:26.2078996Z       Running `flang-new --version` gave "[Errno 2] No such file or directory: 'flang-new'"
2025-07-08T20:38:26.20790202Z       Running `flang-new -V` gave "[Errno 2] No such file or directory: 'flang-new'"
2025-07-08T20:38:26.207904711Z       Running `flang --help` gave "[Errno 2] No such file or directory: 'flang'"
2025-07-08T20:38:26.207907331Z       Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
2025-07-08T20:38:26.207909671Z       Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
2025-07-08T20:38:26.207912121Z       Running `nvfortran --help` gave "[Errno 2] No such file or directory: 'nvfortran'"
2025-07-08T20:38:26.207914781Z       Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
2025-07-08T20:38:26.207917321Z       Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
2025-07-08T20:38:26.207919861Z       Running `pgfortran --help` gave "[Errno 2] No such file or directory: 'pgfortran'"
2025-07-08T20:38:26.207922531Z       Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
2025-07-08T20:38:26.207925061Z       Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
2025-07-08T20:38:26.207927731Z       Running `ifort --help` gave "[Errno 2] No such file or directory: 'ifort'"
2025-07-08T20:38:26.207936851Z       Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
2025-07-08T20:38:26.207942631Z       Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
2025-07-08T20:38:26.207945511Z       Running `ifx --help` gave "[Errno 2] No such file or directory: 'ifx'"
2025-07-08T20:38:26.207947911Z       Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
2025-07-08T20:38:26.207950561Z       Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
2025-07-08T20:38:26.207953071Z       Running `g95 --help` gave "[Errno 2] No such file or directory: 'g95'"
2025-07-08T20:38:26.207955401Z       Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
2025-07-08T20:38:26.207957761Z       Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
2025-07-08T20:38:26.207960341Z       
2025-07-08T20:38:26.208050863Z       A full log can be found at /tmp/pip-install-r41d17sd/scipy_be578535254e4583970332105e5b3908/.mesonpy-dulk_swy/meson-logs/meson-log.txt
2025-07-08T20:38:26.208056933Z       [end of output]
2025-07-08T20:38:26.208059513Z   
2025-07-08T20:38:26.208062243Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2025-07-08T20:38:26.218851308Z error: metadata-generation-failed
2025-07-08T20:38:26.218866499Z 
2025-07-08T20:38:26.218870369Z Ã— Encountered error while generating package metadata.
2025-07-08T20:38:26.218873579Z â•°â”€> See above for output.
2025-07-08T20:38:26.218875909Z 
2025-07-08T20:38:26.218879259Z note: This is an issue with the package mentioned above, not pip.
2025-07-08T20:38:26.218881939Z hint: See above for details.
2025-07-08T20:38:27.089511513Z ==> Build failed ðŸ˜ž
2025-07-08T20:38:27.089541183Z ==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys